### ISSUE TITLE
Which Keycloak version would be supported with 1.0.0?

### ISSUE THREAD

**Issue by JayAhn2** [Herdo/keycloak-remember-me-authenticator#2]
I'm using version 18 due to Apple login, so I would like to which version has been tested with this plugin. (would be nicer if you put this information in README.)

Many thanks for this project.

**Comment by Herdo** [comment]
@JayAhn2 So far I only tested it with version 20.
If you like to test it with version 18, feel free to go ahead and let me know the results.
I'll add information to the `README.md` 👍

**Comment by alexandermalykhin** [comment]
I had tested for 21.1.1
Works fine!

**Comment by Herdo** [comment]
Thank you! 😄

**Comment by FelR** [comment]
Tested this provider with version 22.0.1. Works great! Thank you!
