### ISSUE TITLE
Support for v21

### ISSUE THREAD

**Issue by QuarkAgency** [Herdo/keycloak-remember-me-authenticator#3]
Hello,

I tried to build locally a version by replacing the keycloak version with 21 in pom.xml.
It works fine with IDP but not with email&password flow.
The session is destroyed when browser is closed.

Any idea on what I should change ?

Thanks,

**Comment by Herdo** [comment]
@QuarkAgency My best guess would be that you need to modify the `browser` flow accordingly. When correctly configured, that should do it. Otherwise, I think the user-set checkbox to remember them or not to remember them overwrites the value set by the plugin.
